### ISSUE TITLE
Identify role dependencies for each role, and enforce them accordingly.

### ISSUE THREAD

**Issue by cjnovak98** [cjnovak98/ocp4-disconnected-collection#12]
As stated above, any role dependencies should be defined in the role's main.yml as seen at the link at the bottom of this description. This will ensure proper order of execution, and reduce complexity from the user's perspective, as well as for documentation purposes. Below is an example taken from the below link:

```
# roles/myapp/meta/main.yml
---
dependencies:
  - role: common
    vars:
      some_parameter: 3
  - role: apache
    vars:
      apache_port: 80
  - role: postgres
    vars:
      dbname: blarg
      other_parameter: 12
```

https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_reuse_roles.html#role-argument-validation
